// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicCanvas: typeof import('./src/components/canvas/basic-canvas/BasicCanvas.vue')['default']
    CanvasHolder: typeof import('./src/components/CanvasHolder.vue')['default']
    CanvasTwo: typeof import('./src/components/canvas/canvas-two/CanvasTwo.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
